### ISSUE TITLE
TOML <del>v0.3</del> v0.4 support

### ISSUE THREAD

**Issue by sagotch** [mackwic/To.ml#26]
Changelog [here](https://github.com/toml-lang/toml/blob/master/CHANGELOG.md)

> 0.3.0 / 2014-11-10
>
> Add scientific notation for floats.
> Allow optional + prefix on integers.
> Switch to RFC 3339 for datetimes (allowing offsets and fractional seconds).
> Add multiline and literal strings.
> Clarify what characters valid keys can contain.

It is *may* not to break the API, but valid toml documents for current version will not be valid anymore (mostly because of date format change), so these improvements may lead to a 3.0 version for the library.

**Comment by sagotch** [comment]
Note: I started [date times](https://github.com/mackwic/To.ml/tree/RFC-3339) and [multiline strings](https://github.com/mackwic/To.ml/tree/string) branches.

**Comment by sagotch** [comment]
TOML 0.4 has been [released](https://github.com/toml-lang/toml/releases/tag/v0.4.0)

> 0.4.0 / 2015-02-12
>
>Add Inline Table syntax.
>Allow underscores in numbers.
>Remove forward slash as an escapable character.
>Unicode escapes must be scalar values.
>Newline is now defined as LF or CRLF.

**Comment by sagotch** [comment]
`toml-4.0` branch has implemented some of these features. It is known to miss:
- Underscores in numbers
- Better unicode escape sequences support
- Inline Table

**Comment by Emm** [comment]
@sagotch: I fixed all the tests! Also, the underscore thing should be working now.

**Comment by sagotch** [comment]
Good job.
Should we release a new version with current features instead of waiting for everything to be implemented?
May be an alpha version?

**Comment by Emm** [comment]
On Thu, Oct 22, 2015 at 1:58 PM, Julien Sagot <notifications@github.com>
wrote:

> Good job.
> Should we release a new version with current features instead of waiting
> for everything to be implemented?
> May be an alpha version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mackwic/To.ml/issues/26#issuecomment-150200147>.
>
Well, I'm working adding inline tables. I'd rather get that done, and
release  a 4.0-compatible version.

**Comment by Emm** [comment]
@sagotch, we pass the official example with flying colors. Let me know if you have time to review it, then we can make a 4.0-compatible release.

**Comment by sagotch** [comment]
Nice, I will try to review it tonight at home.
