### ISSUE TITLE
2.2.0 does not compile

### ISSUE THREAD

**Issue by sagotch** [mackwic/To.ml#31]
setup.ml is missing

```
$ make build 
ocaml setup.ml -configure 
Cannot find file setup.ml
```

I will generate gh-pages and fix opam file as soon as Makefile will be fixed.

**Comment by mackwic** [comment]
Yeah, the workflow is `./configure [--enable-tests] && make [test]`.
You need to configure only once.

**Comment by sagotch** [comment]
Oups, sorry about that. :+1:

**Comment by mackwic** [comment]
I'm just happy it's working. :)

**Comment by sagotch** [comment]
Nevertheless, ditributing the project without the `configure` file add a dependency (`oasis`). Not a big deal but the configuration script should be the same for everyone(I guess) so we should include it in versionned files.

**Comment by mackwic** [comment]
yes, it's an error, should have included that. I'll push it now
