### ISSUE TITLE
menhir is required, yet isn't a library

### ISSUE THREAD

**Issue by c-cube** [mackwic/To.ml#35]
In `_oasis`, mehhir is added as a dependency ("XMetaRequires"), but menhir is a binary. It should only be required for compiling, not when linking the library. Subsequently I can't use the library (version 2.2.0).

**Comment by mackwic** [comment]
thanks for the bug report.

So basically, the fix would be to remove "menhir" in [this line](https://github.com/mackwic/To.ml/blob/master/_oasis#L47) in the `_oasis_` file ?

**Comment by c-cube** [comment]
I think so. Why do you need `menhirLib` to build, btw?

**Comment by sagotch** [comment]
As far as I know, you only need the menhir binary in order to compile toml.

**Comment by sagotch** [comment]
@c-cube I just released 2.2.1, so this issue should really be fixed now.

Thanks again for reporting and for you fix :+1:
