### ISSUE TITLE
Error compiling toml on 4.04.0 - ISO8601.cmi compiled with wrong version of compiler

### ISSUE THREAD

**Issue by orbitz** [mackwic/To.ml#46]
I'm not convinced this is actually a TOML issue but I see it when installing TOML.  Note that everything is installed fresh so the error doesn't quite make sense to me.

This is for TOML 4.0.0

    ...
    /usr/local/jenkins/jobs/lua_pattern-4.04.0+flambda-unit-tests/workspace/.opam/4.04.0+flambda/bin/ocamlfind ocamldep -package unix -package str -package ISO8601 -modules src/tomlPrinter.ml > src/tomlPrinter.ml.depends
    /usr/local/jenkins/jobs/lua_pattern-4.04.0+flambda-unit-tests/workspace/.opam/4.04.0+flambda/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package unix -package str -package ISO8601 -I src -o src/tomlLexer.cmo src/tomlLexer.ml
    + /usr/local/jenkins/jobs/lua_pattern-4.04.0+flambda-unit-tests/workspace/.opam/4.04.0+flambda/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package unix -package str -package ISO8601 -I src -o src/tomlLexer.cmo src/tomlLexer.ml
    File "src/tomlLexer.ml", line 1:
    Error: /usr/local/jenkins/jobs/lua_pattern-4.04.0+flambda-unit-tests/workspace/.opam/4.04.0+flambda/lib/ISO8601/ISO8601.cmi
    is not a compiled interface for this version of OCaml.
    It seems to be for an older version of OCaml.
    Command exited with code 2.
    + ocamlfind ocamlopt unix.cmxa -I /usr/local/jenkins/jobs/lua_pattern-4.04.0+flambda-unit-tests/workspace/.opam/4.04.0+flambda/lib/ocamlbuild /usr/local/jenkins/jobs/lua_pattern-4.04.0+flambda-unit-tests/workspace/.opam/4.04.0+flambda/lib/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /usr/local/jenkins/jobs/lua_pattern-4.04.0+flambda-unit-tests/workspace/.opam/4.04.0+flambda/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild

**Comment by mackwic** [comment]
Wow. Sorry, no idea what it could be. Did you made a test with other versions ocaml ?

**Comment by sagotch** [comment]
Any chance that a ```eval `opam config env` ``` has been forgotten at some point?

**Comment by mackwic** [comment]
Closing by lack if activity
