### ISSUE TITLE
new maintainer(s)?

### ISSUE THREAD

**Issue by c-cube** [mackwic/To.ml#54]
given #53 it'd be nice if @mackwic could give commit rights to other people. I'd be happy to step in for maintenance, making new releases, etc.

**Comment by mackwic** [comment]
You have been make a collaborator. Welcome to the club. :)

***

As an aside, and for general information: I am very open to new maintainers. @Emm, @sagotch, and @prepor are already collaborators for their contributions.

Everyone with an open mind and a will to help is welcome. Just ask. Or contribute. Any non-trivial PR will make you a contributor.
